<?php

declare(strict_types=1);

namespace Cbu\Currency\Enums;

/**
 * ISO 4217 Numeric Currency Codes
 *
 * @see https://en.wikipedia.org/wiki/ISO_4217
 */
enum CurrencyNumericCode: int
{
    case ALL = 8; // Lek
    case DZD = 12; // Algerian Dinar
    case ARS = 32; // Argentine Peso
    case AUD = 36; // Australian Dollar
    case BSD = 44; // Bahamian Dollar
    case BHD = 48; // Bahraini Dinar
    case BDT = 50; // Taka
    case AMD = 51; // Armenian Dram
    case BBD = 52; // Barbados Dollar
    case BMD = 60; // Bermudian Dollar
    case BTN = 64; // Ngultrum
    case BOB = 68; // Boliviano
    case BWP = 72; // Pula
    case BZD = 84; // Belize Dollar
    case SBD = 90; // Solomon Islands Dollar
    case BND = 96; // Brunei Dollar
    case MMK = 104; // Kyat
    case BIF = 108; // Burundi Franc
    case KHR = 116; // Riel
    case CAD = 124; // Canadian Dollar
    case CVE = 132; // Cabo Verde Escudo
    case KYD = 136; // Cayman Islands Dollar
    case LKR = 144; // Sri Lanka Rupee
    case CLP = 152; // Chilean Peso
    case CNY = 156; // Yuan Renminbi
    case COP = 170; // Colombian Peso
    case KMF = 174; // Comorian Franc
    case CRC = 188; // Costa Rican Colon
    case HRK = 191; // Kuna
    case CUP = 192; // Cuban Peso
    case CZK = 203; // Czech Koruna
    case DKK = 208; // Danish Krone
    case DOP = 214; // Dominican Peso
    case SVC = 222; // El Salvador Colon
    case ETB = 230; // Ethiopian Birr
    case ERN = 232; // Nakfa
    case FKP = 238; // Falkland Islands Pound
    case FJD = 242; // Fiji Dollar
    case DJF = 262; // Djibouti Franc
    case GMD = 270; // Dalasi
    case GIP = 292; // Gibraltar Pound
    case GTQ = 320; // Quetzal
    case GNF = 324; // Guinean Franc
    case GYD = 328; // Guyana Dollar
    case HTG = 332; // Gourde
    case HNL = 340; // Lempira
    case HKD = 344; // Hong Kong Dollar
    case HUF = 348; // Forint
    case ISK = 352; // Iceland Krona
    case INR = 356; // Indian Rupee
    case IDR = 360; // Rupiah
    case IRR = 364; // Iranian Rial
    case IQD = 368; // Iraqi Dinar
    case ILS = 376; // New Israeli Sheqel
    case JMD = 388; // Jamaican Dollar
    case JPY = 392; // Yen
    case KZT = 398; // Tenge
    case JOD = 400; // Jordanian Dinar
    case KES = 404; // Kenyan Shilling
    case KPW = 408; // North Korean Won
    case KRW = 410; // Won
    case KWD = 414; // Kuwaiti Dinar
    case KGS = 417; // Som
    case LAK = 418; // Lao Kip
    case LBP = 422; // Lebanese Pound
    case LSL = 426; // Loti
    case LRD = 430; // Liberian Dollar
    case LYD = 434; // Libyan Dinar
    case MOP = 446; // Pataca
    case MWK = 454; // Malawi Kwacha
    case MYR = 458; // Malaysian Ringgit
    case MVR = 462; // Rufiyaa
    case MUR = 480; // Mauritius Rupee
    case MXN = 484; // Mexican Peso
    case MNT = 496; // Tugrik
    case MDL = 498; // Moldovan Leu
    case MAD = 504; // Moroccan Dirham
    case OMR = 512; // Rial Omani
    case NAD = 516; // Namibia Dollar
    case NPR = 524; // Nepalese Rupee
    case ANG = 532; // Netherlands Antillean Guilder
    case AWG = 533; // Aruban Florin
    case VUV = 548; // Vatu
    case NZD = 554; // New Zealand Dollar
    case NIO = 558; // Cordoba Oro
    case NGN = 566; // Naira
    case NOK = 578; // Norwegian Krone
    case PKR = 586; // Pakistan Rupee
    case PAB = 590; // Balboa
    case PGK = 598; // Kina
    case PYG = 600; // Guarani
    case PEN = 604; // Sol
    case PHP = 608; // Philippine Peso
    case QAR = 634; // Qatari Rial
    case RUB = 643; // Russian Ruble
    case RWF = 646; // Rwanda Franc
    case SHP = 654; // Saint Helena Pound
    case SAR = 682; // Saudi Riyal
    case SCR = 690; // Seychelles Rupee
    case SLL = 694; // Leone
    case SGD = 702; // Singapore Dollar
    case VND = 704; // Dong
    case SOS = 706; // Somali Shilling
    case ZAR = 710; // Rand
    case SSP = 728; // South Sudanese Pound
    case SZL = 748; // Lilangeni
    case SEK = 752; // Swedish Krona
    case CHF = 756; // Swiss Franc
    case SYP = 760; // Syrian Pound
    case THB = 764; // Baht
    case TOP = 776; // Pa'anga
    case TTD = 780; // Trinidad and Tobago Dollar
    case AED = 784; // UAE Dirham
    case TND = 788; // Tunisian Dinar
    case UGX = 800; // Uganda Shilling
    case MKD = 807; // Denar
    case EGP = 818; // Egyptian Pound
    case GBP = 826; // Pound Sterling
    case TZS = 834; // Tanzanian Shilling
    case USD = 840; // US Dollar
    case UYU = 858; // Peso Uruguayo
    case UZS = 860; // Uzbekistan Sum
    case WST = 882; // Tala
    case YER = 886; // Yemeni Rial
    case TWD = 901; // New Taiwan Dollar
    case UYW = 927; // Unidad Previsional
    case VES = 928; // Bolívar Soberano
    case MRU = 929; // Ouguiya
    case STN = 930; // Dobra
    case CUC = 931; // Peso Convertible
    case ZWL = 932; // Zimbabwe Dollar
    case BYN = 933; // Belarusian Ruble
    case TMT = 934; // Turkmenistan New Manat
    case GHS = 936; // Ghana Cedi
    case SDG = 938; // Sudanese Pound
    case UYI = 940; // Uruguay Peso en Unidades Indexadas (UI)
    case RSD = 941; // Serbian Dinar
    case MZN = 943; // Mozambique Metical
    case AZN = 944; // Azerbaijan Manat
    case RON = 946; // Romanian Leu
    case CHE = 947; // WIR Euro
    case CHW = 948; // WIR Franc
    case TRY = 949; // Turkish Lira
    case XAF = 950; // CFA Franc BEAC
    case XCD = 951; // East Caribbean Dollar
    case XOF = 952; // CFA Franc BCEAO
    case XPF = 953; // CFP Franc
    case XBA = 955; // Bond Markets Unit European Composite Unit (EURCO)
    case XBB = 956; // Bond Markets Unit European Monetary Unit (E.M.U.-6)
    case XBC = 957; // Bond Markets Unit European Unit of Account 9 (E.U.A.-9)
    case XBD = 958; // Bond Markets Unit European Unit of Account 17 (E.U.A.-17)
    case XAU = 959; // Gold
    case XDR = 960; // SDR (Special Drawing Right)
    case XAG = 961; // Silver
    case XPT = 962; // Platinum
    case XTS = 963; // Codes specifically reserved for testing purposes
    case XPD = 964; // Palladium
    case XUA = 965; // ADB Unit of Account
    case ZMW = 967; // Zambian Kwacha
    case SRD = 968; // Surinam Dollar
    case MGA = 969; // Malagasy Ariary
    case COU = 970; // Unidad de Valor Real
    case AFN = 971; // Afghani
    case TJS = 972; // Somoni
    case AOA = 973; // Kwanza
    case BGN = 975; // Bulgarian Lev
    case CDF = 976; // Congolese Franc
    case BAM = 977; // Convertible Mark
    case EUR = 978; // Euro
    case MXV = 979; // Mexican Unidad de Inversion (UDI)
    case UAH = 980; // Hryvnia
    case GEL = 981; // Lari
    case BOV = 984; // Mvdol
    case PLN = 985; // Zloty
    case BRL = 986; // Brazilian Real
    case CLF = 990; // Unidad de Fomento
    case XSU = 994; // Sucre
    case USN = 997; // US Dollar (Next day)
    case XXX = 999; // The codes assigned for transactions where no currency is involved
}
